on:
    push:
        paths:
            - "packages/components/src/**"
        branches: [main]
    pull_request:
        paths:
            - "packages/components/src/**"
        branches: [main]
    workflow_call:

jobs:
    call-coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: "./.github/workflows/coverage.yml"
              with:
                  package: components
