name: build
on:
    push:
        paths:
            - "packages/components/**"
        branches: [main]
    pull_request:
        paths:
            - "packages/components/**"
        branches: [main]

jobs:
    call-build:
        uses: ./.github/workflows/build.yml
        with:
            package: components
