name: "coverage template"

on:
    workflow_call:
        inputs:
            package:
                required: true
                type: string

jobs:
    coverage:
        name: "'${{ inputs.package }}' Test Coverage"
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/${{ inputs.package }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Install Dependencies
              run: npm ci --workspaces=false

            - name: Run Coverage
              run: npm run test:cov
