on:
    push:
        paths:
            - "packages/mvc/src/**"
        branches: [main]
    pull_request:
        paths:
            - "packages/mvc/src/**"
        branches: [main]
    workflow_dispatch:

jobs:
    call-coverage:
        uses: "./.github/workflows/coverage.yml"
        with:
            package: mvc
