name: build
on:
    push:
        paths:
            - "packages/mvc/**"
        branches: [main]
    pull_request:
        paths:
            - "packages/mvc/**"
        branches: [main]

jobs:
    call-build:
        name: "'mvc' build"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.event.repository.default_branch }}
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - uses: ./.github/actions/build/
              with:
                  package: mvc
