name: "build"

on:
    push:
        paths:
            - "packages/stateful/**"
        branches: [main]
    pull_request:
        paths:
            - "packages/stateful/**"
        branches: [main]

jobs:
    tests:
        name: Tests and Coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "22"
            - name: Install
              run: npm ci -w=packages/stateful

            - name: Run Tests and Coverage
              run: npm run test:cov -w=packages/stateful

            - name: Update Coverage Badge
              if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
              uses: we-cli/coverage-badge-action@main

    build:
        name: Run build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "22"
            - run: npm ci -w=packages/stateful
            - run: npm run build -w=packages/stateful
