on:
    push:
        paths:
            - "packages/stateful/src/**"
        branches: [main]
    pull_request:
        paths:
            - "packages/stateful/src/**"
        branches: [main]
    workflow_call:

jobs:
    call-coverage:
        uses: "./.github/workflows/coverage.yml"
        with:
            package: stateful
