name: "unit tests"

on:
    push:
        paths:
            - "packages/stateful/src/**"
        branches: [main]
    pull_request:
        paths:
            - "packages/stateful/src/**"
        branches: [main]

jobs:
    test:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "22"

            - name: Clean Install
              run: npm ci -w=packages/stateful

            - name: Run Tests
              run: npm run test -w=packages/stateful
