name: build
on:
    push:
        paths:
            - "packages/stateful/**"
        branches:
            - "**"
    pull_request:
        paths:
            - "packages/stateful/**"
        branches: [main]
    workflow_call:

jobs:
    call-build:
        name: "'stateful' build"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - uses: ./.github/actions/build/
              with:
                  package: stateful
