name: "coverage"

on:
    push:
        paths:
            - "packages/stateful/**"
    pull_request:
        paths:
            - "packages/stateful/**"
    workflow_dispatch:

jobs:
    tests:
        name: Tests and Coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "22"

            - name: Clean Install
              run: npm ci -w=packages/stateful

            - name: Run Coverage
              run: npm run test:cov -w=packages/stateful

            - name: Copy coverage folder to root
              run: cp -r /packages/stateful/coverage

            - name: Update Coverage Badge
              if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
              uses: we-cli/coverage-badge-action@main
